name: Build and Push Docker Image Into ECR And Scan the Image

on: 
  push: 
     branches: ['main']
  pull_request:
     branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nodejs-ecr-repo
        run: |
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_number }} .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Send Email Notification on Success
        if: success()  # Condition to check if the previous step was successful
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: bhaskarmehta422@gmail.com
          subject: 'Docker image upload successful'
          to: 'bhaskarmehta12@gmail.com, bhaskarmehta22@gmail.com'
          body: 'The Docker image was successfully uploaded to ECR.'

      - name: Send Email Notification on Failure
        if: failure()  # Condition to check if the previous step failed
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: bhaskarmehta422@gmail.com
          subject: 'Docker image upload failed'
          to: 'bhaskarmehta12@gmail.com, bhaskarmehta22@gmail.com'
          body: 'There was a failure while uploading the Docker image to ECR. Please check the workflow logs.'         
    

      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy

      - name: Scan Docker Image for Vulnerabilities
        run: trivy image 629884197199.dkr.ecr.eu-north-1.amazonaws.com/nodejs-ecr-repo:${{ github.run_number }}  
